# Generated by Django 5.2.6 on 2025-11-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempost',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='価格'),
        ),
    ]
